name: mumi
on: [push]
jobs:
  check-bats-version_und_ls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: ls
      - run: cd Code
      - run: ls
      - run: echo "Hello World"
      - run: echo $PATH
      - name: Display the path
        run: cd Code
        shell: sh
