name: mumi
on: [push]
jobs:
  check-bats-version_und_ls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: ls
      - uses: xanderhendriks/action-build-stm32cubeide@v5.0
        with:
          project-path: 'GATEWAY.DINA.CX.APP/'
          project-target: 'GATEWAY.DINA.CX/.project'
      - run: ls
